### PR TITLE
Add ERD

### PR DESCRIPTION
**Pull request by SuyashFowdar**
In this feature, the ERD has been created containing the list of fields each table will have and the relationships between each table.

Thank you.

### CODE REVIEW

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @krishnzzz :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
#### :warning: However we need to make few changes to mark this project approved. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [ ] You are missing the table `comments`, please add it to the ERD
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
.

**Review by teekaytech — CHANGES_REQUESTED** [review]
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello team :wave:

__Your ERD is awesome. Everything is looking good.
However, some changes are required before this milestone can be approved. Please check my comments below and fix them as appropriate.__

**[ REQUIRED CHANGES ]**

- [x] Your linter checks (GitHub Actions) are not running. For all the milestones in this project, always ensure that the linter checks are running and all checks are passed on your PR page, before requesting for review.
- [x] The `Like` entity is missing. Since one of the logged_in users' feature is the **ability to like/dislike posts**, this entity (like) is also required. The entity will consist of the `user_id` and the `post_id`.



* * *
**Please make the required changes and submit another review request when you are done.**

* * *

**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

**Comment by mimipeshy** [comment]
### STATUS :APPROVED :partying_face: 

Hey there @krishnzzz  :wave: :wave: good job on working on the requested changes. This project is therefore approved. Go ahead and merge. All the best in the next milestones :man_technologist: 

Regards
Peris Ndanu

**Pull request merged**
