### PR TITLE
Friendship v1 feature

### PR DESCRIPTION
**Pull request by SuyashFowdar**
In this feature, the following options have been added:

- Ability to create a new friendship request
- Ability to cancel the friendship request
- Ability to accept the friendship request by other user
- Ability to decline the friendship request by other user
- Ability to remove one from friendship list

Thank you.

### CODE REVIEW

**Review by LamiaSristy — CHANGES_REQUESTED** [review]
# Status: Change Required. ♻️

Hello @krishnzzz  🙌

Great work so far.

You need to implement the works below to get the project approved!🛠️

Please check my points here: 👇

`[REQUIRED]`

- [ ] **You need to add Unit and Integration tests!** ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/tests.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))


Please make the changes and ask for a re-review.

Feel free to reach me at @lamiasristy 🙋

**Review by rindrajosia — CHANGES_REQUESTED** [review]
**Changes required**
Hello Team!!
You did a very good job.
However, to move forward you have to make some changes:
REQUIRED:
- [x] I should be able to see **only** "Posts" `written by me` and `my friends`.([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

As you can see in this screenshot, Josia is not yet Marina's friend however, Marina can see Josia's Post.

- [x] There is a button to invite user to friendship on users list page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

You should add `a button to invite user to friendship` on this page.

Please, make the suggested changes and submit a new code review request
Thanks
Rindra Josia

**Comment by mimipeshy** [comment]
#### STATUS : CHANGES REQUIRED :red_circle: :recycle: 

Hey, team @krishnzzz great job on working on this project. You have tried to implement all changes requested except for one as I noted below

- [ ]  There is a button to invite user to friendship on users list page and on single-user page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)) You should `add a button to invite user to friendship on this page.` Currently, I have to go to the user's profile to send a request or decline it. 

image

That's all :smile: kindly submit another review when done.

_Feel free to reach out to me on slack if you have any questions or something is unclear, I will be glad to help_
Regards
Peris Ndanu

**Comment by SuyashFowdar** [comment]
Screenshot_20210201_194620

@mimipeshy ,

If you will pull the latest version, you will find it already implemented as in the screenshot.

Thank you.

**Review by Temmarie — APPROVED** [review]
## Status: Approved :heavy_check_mark:

### Hi @krishnzzz  ! :wave:

#### Thank you for making all of the required changes, your project is approved :clap: :clap: :clap: :tada:
 
#### You may merge, good luck with your next projects! :rocket:
#### Happy Coding! :+1:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Pull request merged**
